steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
         '$_GCR_HOSTNAME/$PROJECT_ID/terraform-template/image:$SHORT_SHA', '.']

# Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/terraform-template/image:$SHORT_SHA']

# Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_SERVICE_NAME',
           '--image=$_GCR_HOSTNAME/$PROJECT_ID/terraform-template/image:$SHORT_SHA',
           '--region', '$_DEPLOY_REGION', '--platform', 'managed']

images:
  - $_GCR_HOSTNAME/$PROJECT_ID/terraform-template/image:$SHORT_SHA

substitutions:
  _GCR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _DEPLOY_REGION: asia-northeast1
  _SERVICE_NAME: terraform-template